version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: on-failure
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: Neobank_Database
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
