dbt_projectNeo:
  outputs:
    dev:
      dataset: neobank
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /app/airflow/.gcp_keys/le-wagon-de-bootcamp.json
      location: EU
      method: service-account
      priority: interactive
      project: modern-water-402010
      threads: 1
      type: bigquery


    prod:
      dataset: neobank
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/ahalenke/.gcp_keys/le-wagon-de-bootcamp.json
      location: EU
      method: service-account
      priority: interactive
      project: modern-water-402010
      threads: 1
      type: bigquery

  target: dev
