dbt_projectNeo:
  outputs:
    dev:
      dataset: neobank
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GCP_KEYFILE_PATH') }}"
      location: "{{ env_var('GCP_LOCATION') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 1
      type: bigquery
  target: dev
