dbt_projectNeo:
  outputs:
    silver:
      dataset: dbt_alexhalenke_silver_23032024
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/ahalenke/.gcp_keys/le-wagon-de-bootcamp.json
      location: EU
      method: service-account
      priority: interactive
      project: modern-water-402010
      threads: 1
      type: bigquery
    gold:
      dataset: dbt_alexhalenke_gold_27032024
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/ahalenke/.gcp_keys/le-wagon-de-bootcamp.json
      location: EU
      method: service-account
      priority: interactive
      project: modern-water-402010
      threads: 1
      type: bigquery
  target: dev
