version: 2

models:
  - name: device_table
    columns:
      - name: device_type
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null
          - unique

  - name: user_table
    columns:
      - name: user_id
        tests:
          - not_null
          - unique

  - name: notification_table
    columns:
      - name: user_id
        tests:
          - not_null
          - unique

  - name: transaction_table
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
      - name: transaction_id
        tests:
          - not_null
          - unique
