version: 2

sources:
  - name: 02_silver
    dataset: Silver_Tier
    tables:
      - name: date_dim
      - name: device_notification_dim
      - name: transactions_facts
      - name: merchant_dim
      - name: user_country_dim
      - name: users_dim
